const NOTIFICATION_TYPES = {
    USER_FOLLOW: 'FOLLOW',
    POST_FOLLOW: 'reset password',
    COMMENT_LIKE: 'COMMENT_LIKE',
    POST_LIKE: 'comment by like',
    POST_VOTE: 'post by @',
    COMMENT: 'comment by @',
    COMMENT_FOLLOWED_POST: 'COMMENT_FOLLOWED_POST',
    SURVEY_PENDING: 'SURVEY_PENDING',
    ADMIN_SURVEY_PENDING: 'ADMIN_SURVEY_PENDING',
}
// const NOTIFICATION_TYPES = {
//     USER_FOLLOW: 'FOLLOW',
//     POST_FOLLOW: 'POST_FOLLOW',
//     COMMENT_LIKE: 'COMMENT_LIKE',
//     POST_LIKE: 'POST_LIKE',
//     POST_VOTE: 'POST_VOTE',
//     COMMENT: 'COMMENT',
//     COMMENT_FOLLOWED_POST: 'COMMENT_FOLLOWED_POST',
//     SURVEY_PENDING: 'SURVEY_PENDING',
//     ADMIN_SURVEY_PENDING: 'ADMIN_SURVEY_PENDING',
// }

export default NOTIFICATION_TYPES
